name: cicd Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Compile:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  SecurityCheck:
    runs-on: self-hosted
    needs: Compile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 for Scanner
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Resolve Dependencies Locally
        run: mvn dependency:go-offline -B --file pom.xml

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'fs-report.json'
          severity: 'CRITICAL,HIGH'

      - name: Gitleaks Installation
        run: sudo apt-get install gitleaks -y

      - name: Gitleaks Code Scan
        run: gitleaks detect --source . -r gitleaks-report.json -f json

  UnitTest:
    runs-on: self-hosted
    needs: SecurityCheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test --file pom.xml
